version: '3'
services:

  ### MySQL db for Keycloak server to persist data
  keycloak-mysql:
    image: mysql:8
    container_name: KEYCLOAK_MYSQL
    restart: unless-stopped
    volumes:
      - ./db-data/MySQL/keycloak:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak

  ### KeyCloak-Server
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: KEYCLOAK-SERVER
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realm/:/opt/keycloak/data/import
    depends_on:
      - keycloak-mysql

  ### Redis
  redis:
    image: redis:7.2.3
    container_name: REDIS
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - ./db-data/Redis:/data